Pushing source code for others

diff --git a/src/jobs/destroy.yml b/src/jobs/destroy.yml
--- a/src/jobs/destroy.yml
+++ b/src/jobs/destroy.yml
@@ -44,6 +44,13 @@ parameters:
       A CircleCI generated namespace for your organization. Please see
       https://circleci.com/docs/2.0/orb-concepts/#namespaces for more details.
     type: env_var_name
+  resource_class:
+    description: |
+      Name of the resource class that will be generated and used for On Demand Runners.
+      If you do not have a resource class to use, please pass in 'pipeline.id'. Generally, it best
+      practice to pass in 'pipeline.id'. PLEASE note you need to set resource class to a 
+      name that is not currently being used, as the resource class will be deleted.
+    type: string
   number_of_numbers:
     default: NUMBER_OF_RUNNERS
     description: |
@@ -73,7 +80,58 @@ parameters:
     description: Ansible Version To Be Installed
     type: string
 steps:
-  - install-ansible:
-      version: <<parameters.version>>
-  - install-dependencies
-  - deprovision
+  - run:
+      name: Installing Ansible <<parameters.version>>
+      command: |
+        export PIP=$(which pip pip3 | head -1)
+        if [[ -n $PIP ]]; then
+          if command -v ansible &> /dev/null
+          then
+            echo "Ansible is already installed thus skipping install."
+          else
+            $PIP install 'ansible==<<parameters.version>>'
+          fi
+        else
+          echo "Unable to install Ansible! Please install Pip First."
+          exit 1
+        fi
+
+  - run:
+      name: Install boto3 & botocore
+      command: |
+        export PIP=$(which pip pip3 | head -1)
+        if [[ -n $PIP ]]; then
+            $PIP install boto3 botocore --upgrade
+        else
+          echo "Unable to install boto3 and botocore! Please install Pip First."
+          exit 1
+        fi
+
+  - run:
+      name: Install amazon.aws
+      command: ansible-galaxy collection install amazon.aws
+
+  - run:
+      name: Install community.general
+      command: ansible-galaxy collection install community.general
+
+  - run:
+      name: Setting Defaults if Variables are not Set
+      command: |
+          echo "export AWS_DEFAULT_REGION=$(echo ${AWS_DEFAULT_REGION:-US-EAST-1})" >> $BASH_ENV
+          echo "export RESOURCE_CLASS=$(echo ${RESOURCE_CLASS:-<< parameters.resource_class	>>})" >> $BASH_ENV
+          echo "export NUMBER_OF_RUNNERS=$(echo ${NUMBER_OF_RUNNERS:-1})" >> $BASH_ENV
+          echo "export NUMBER_OF_WAITS=$(echo ${NUMBER_OF_WAITS:-18})" >> $BASH_ENV
+          echo "export ANSIBLE_FORCE_COLOR=$(echo ${ANSIBLE_FORCE_COLOR:-true})" >> $BASH_ENV
+          echo "export ANSIBLE_GIT_URL=$(echo ${ANSIBLE_GIT_URL:-https://github.com/james-crowley/on-demand-runners.git})" >> $BASH_ENV
+          echo "export ANSIBLE_GIT_BRANCH=$(echo ${ANSIBLE_GIT_BRANCH:-main})" >> $BASH_ENV
+          source $BASH_ENV
+
+  - run: Clone On Demand Runner Ansible from Github
+    command: |
+        git clone ${ANSIBLE_GIT_URL} && cd ./on-demand-runners && git checkout ${ANSIBLE_GIT_BRANCH}
+  
+  - run: Deprovision On Demand Runners
+    working_directory: ~/project/on-demand-runners/auto-runner/
+    command: |
+        ansible-playbook deprovision-on-demand-runners.yml -e "REGION=$AWS_DEFAULT_REGION SSH_KEY_NAME=$AWS_SSH_KEY NAMESPACE=$CIRCLECI_NAMESPACE RESOURCE_CLASS=$RESOURCE_CLASS CIRCLE_TOKEN=$CIRCLE_TOKEN NUMBER_OF_RUNNERS=$NUMBER_OF_RUNNERS UNTIL_RETRIES_RUNNERS=$NUMBER_OF_WAITS RESOURCE_CLASS_CREATION=true RUNNER_TOKEN_CREATION=true TEMPLATE_DYNAMIC_INVENTORY=true CLOUD_PROVIDER=aws"
